### ISSUE TITLE
[FE 1.0.1] [SUGGESTION] Launching in fullscreen cannot see cursor, shouldn't be launching in fullscreen anyway

### ISSUE THREAD

**Issue by Xetaxheb** [gamerpotion/DarkRPG#10]
There are several various reasons launching in fullscreen by default is problematic, in my case I cannot see the cursor so it is an incredible struggle to get into settings and change it, but there are numerous reasons that people may encounter depending on their setup.
Plus, if people want it it's easy enough for them to opt-into from windowed mode.

**Comment by gamerpotion** [comment]
> There are several various reasons launching in fullscreen by default is problematic, in my case I cannot see the cursor so it is an incredible struggle to get into settings and change it, but there are numerous reasons that people may encounter depending on their setup. Plus, if people want it it's easy enough for them to opt-into from windowed mode.

Hi, just wanted to check, if it launches in fullscreen, and then you press F11,  does it go into windowed mode for you then?  have you tried that?

**Comment by Xetaxheb** [comment]
Yeah, 
    although it felt unreliable during loading (works in testing now and didn't when I was trying the other day) and locking the users pc down for however long that takes isn't great.
The way the client handled full-screen first launch also didn't respect native resolution for some reason? so all the things I had open got resized (which was a problem for various things.).

And people may not know F11 or not have good access to it (say, laptop keyboards).

_blah blah blah tl;dr_: I think the population of people running in exclusive fullscreen (vs maximized windowed or windowed) doesn't endorse setting it as default. If you disagree feel free to leave it as is.

**Comment by gamerpotion** [comment]
Hi, sure no worries, I will see if there are more people with cursor issues and if so, I will make it default windowed mode.
I think the native resolution thing is to do with the loading screen mod which I have just now updated a setting on so hopefully it will respect people's resolutions! Thanks for the update on this ;)
