### ISSUE TITLE
CurseForge Project Distribution

### ISSUE THREAD

**Issue by JulianVennen** [gamerpotion/DarkRPG#11]
Hi, I work at Aternos (a Minecraft server host) and I'm in charge of managing Modpacks that can be installed on our servers with a single click. This modpack is one of them.

CurseForge recently rolled out an API change that means that it's no longer possible to download files from the API if the modpack author has the option "Allow the Distribution of this project outside the CurseForge-Overwolf ecosystem" disabled.

That option is disabled for this Modpack, which means we can no longer update the pack.
I wanted to ask you if this is intended.
If you don't want to enable that option, I would remove the modpack from our system.

**Comment by gamerpotion** [comment]
Hi sorry I forgot to do that.
I have enabled it on both versions of DarkRPG now, so should be able to update the packs depending on which one is required

[https://www.curseforge.com/minecraft/modpacks/darkrpg](https://www.curseforge.com/minecraft/modpacks/darkrpg)
[https://www.curseforge.com/minecraft/modpacks/darkrpg-forge](https://www.curseforge.com/minecraft/modpacks/darkrpg-forge)

**Comment by JulianVennen** [comment]
Thanks!

**Comment by gamerpotion** [comment]
Hi :)
just to update that version 3.1d of serverpack is now live, if that could be updated on Aternos thanks

**Comment by JulianVennen** [comment]
The pack is up to date now
