### ISSUE TITLE
Quest not working

### ISSUE THREAD

**Issue by Mykola2345** [gamerpotion/DarkRPG#12]
so i have a quest to get 5 redstones it shows me that i have none even tho i have like 46 redstones

**Comment by gamerpotion** [comment]
> so i have a quest to get 5 redstones it shows me that i have none even tho i have like 46 redstones

hi, could you try to place them in a chest then take them out again and see if that works?

**Comment by Mykola2345** [comment]
> > so i have a quest to get 5 redstones it shows me that i have none even tho i have like 46 redstones
> 
> hi, could you try to place them in a chest then take them out again and see if that works?

yep, i tried that even tho i killed myself like 10 times still doesnt work

**Comment by gamerpotion** [comment]
> > > so i have a quest to get 5 redstones it shows me that i have none even tho i have like 46 redstones
> > 
> > 
> > hi, could you try to place them in a chest then take them out again and see if that works?
> 
> yep, i tried that even tho i killed myself like 10 times still doesnt work

Hi, this will be fixed in the next upcoming update 2.8f, please wait for that and update when its released.

**Comment by Mykola2345** [comment]
> > > > so i have a quest to get 5 redstones it shows me that i have none even tho i have like 46 redstones
> > > 
> > > 
> > > hi, could you try to place them in a chest then take them out again and see if that works?
> > 
> > 
> > yep, i tried that even tho i killed myself like 10 times still doesnt work
> 
> Hi, this will be fixed in the next upcoming update 2.8f, please wait for that and update when its released.

when is next update going to come out, because i want to finish this modpack i really like it

**Comment by gamerpotion** [comment]
> > > > > so i have a quest to get 5 redstones it shows me that i have none even tho i have like 46 redstones
> > > > 
> > > > 
> > > > hi, could you try to place them in a chest then take them out again and see if that works?
> > > 
> > > 
> > > yep, i tried that even tho i killed myself like 10 times still doesnt work
> > 
> > 
> > Hi, this will be fixed in the next upcoming update 2.8f, please wait for that and update when its released.
> 
> when is next update going to come out, because i want to finish this modpack i really like it

Hi, no problem. Version 2.8f is now updated. please go ahead and download the latest version and that quest should be fixed.
