### ISSUE TITLE
quests not showing up

### ISSUE THREAD

**Issue by azax123** [gamerpotion/DarkRPG#13]
my friend started a server with all the mods from the curse forge right, how come when i press i there are no quests there? its just a blank screen of gray.

**Comment by gamerpotion** [comment]
Hi, you need to make sure there is a folder in the config folder called ftbquests.  I think its probably the way the files got uploaded and it skipped those folders.
Also are you using the Fabric or Forge version?

**Comment by azax123** [comment]
now when my friend loaded the files in right, the quests work. but now it says the server does not have origins installed?

**Comment by gamerpotion** [comment]
> now when my friend loaded the files in right, the quests work. but now it says the server does not have origins installed?

Hi, just make sure that the origins JAR file is inside the mods folder on the server
does it let you choose an origin?
also if quests are now working, press (i) then on the top right click the emergency items button, then wait few minutes on that screen and it should give you an orb of origin,  then you can use that to change your origin and see if the mod works or not
