### ISSUE TITLE
Quest not working

### ISSUE THREAD

**Issue by Aarrn33** [gamerpotion/DarkRPG#14]
Ok, so first of all, the modpack's great.
Second thing, even though me and my friend use 2.8f on our server some quests don't work properly.
The first time happenned with the dirt quest, i had to quit and get back on the server to complete it but for the lava quest we can't seem to figure out how to complete it. We got a lava bucket, we put it in a chest, dropped, dropped it and then rellogged on the server but still, the quest isn't complete.
Is there any way to manually complete the quest, like with a command or something like that ?

**Comment by gamerpotion** [comment]
> Ok, so first of all, the modpack's great. Second thing, even though me and my friend use 2.8f on our server some quests don't work properly. The first time happenned with the dirt quest, i had to quit and get back on the server to complete it but for the lava quest we can't seem to figure out how to complete it. We got a lava bucket, we put it in a chest, dropped, dropped it and then rellogged on the server but still, the quest isn't complete. Is there any way to manually complete the quest, like with a command or something like that ?

Hi sorry some of the quests can be buggy on the quest mod.  I will fix those by changing the way they are submitted in the next update 2.8f1 (hotfix)  I will try and upload that today so keep an eye out for that.  For the server you will have to override the config folder and restart and it should update

**Comment by Aarrn33** [comment]
OK I'll try that once the update is out!

**Comment by gamerpotion** [comment]
> OK I'll try that once the update is out!

Hi, you can get the updates now, its all approved on CurseForge
