### ISSUE TITLE
Player character death issue

### ISSUE THREAD

**Issue by Deathmoon1998** [gamerpotion/DarkRPG#15]
Me and my friend are playing the Darkrpg modpack together. I have a fully decked out Lilith's Bow from the MobZ mod. After shooting my friend with the bow while we were doing some pvp he ran out of hearts but didn't die. The player walking animation was also glitched in a way that he wasn't walking but sliding everywhere. He also couldn't do anything aside from moving around and opening doors. Trying to kill him with /kill did nothing as well. No matter what we tried to do it didn't bring him out of that glitched state. With the way it is now we might have to start all over on a fresh server and lose all that progress we made. Any ideas on how to fix it?

**Comment by gamerpotion** [comment]
> Me and my friend are playing the Darkrpg modpack together. I have a fully decked out Lilith's Bow from the MobZ mod. After shooting my friend with the bow while we were doing some pvp he ran out of hearts but didn't die. The player walking animation was also glitched in a way that he wasn't walking but sliding everywhere. He also couldn't do anything aside from moving around and opening doors. Trying to kill him with /kill did nothing as well. No matter what we tried to do it didn't bring him out of that glitched state. With the way it is now we might have to start all over on a fresh server and lose all that progress we made. Any ideas on how to fix it?

Hi could you possibly link a screenshot of your friend's screen that shows their XP stats?

**Comment by Deathmoon1998** [comment]
Hello, unfortunately my friend decided to erase the old server and make a completely new server and i couldn't get any screenshots. However if we encounter that issue again i will get screenshots for you. Also sorry for wasting a bit of your time.
