### ISSUE TITLE
Its not allowing me to join the online server

### ISSUE THREAD

**Issue by DannyBub0** [gamerpotion/DarkRPG#18]
![image](https://user-images.githubusercontent.com/109224063/178742417-21472f75-0e38-4c3b-a022-3bcb344bbe99.png)

**Comment by gamerpotion** [comment]
> ![image](https://user-images.githubusercontent.com/109224063/178742417-21472f75-0e38-4c3b-a022-3bcb344bbe99.png)

hi, you need to update to the latest version of modpack which is 3.1b in which that mod was added. If you update to 3.1b you will stop seeing that message
