### ISSUE TITLE
It says it need origins v1.4.1

### ISSUE THREAD

**Issue by notmavek** [gamerpotion/DarkRPG#19]
So when i was creating a server for me and my friends we both had an issue that say we need v1.4.1 so we  try multiple ways but it didn't work

**Comment by thinhofdakh** [comment]
I also encountered similar problems. all other modpacks i have made server work smoothly and same usage. but your modpack got an error asking for origins v1.4.1.

**Comment by gamerpotion** [comment]
> I also encountered similar problems. all other modpacks i have made server work smoothly and same usage. but your modpack got an error asking for origins v1.4.1.

if its asking for origins 1.4.1 it means its not loaded into the mods folder properly.
check your server installation making sure origins jar file is inside the mods folder
then run the actual DarkRPG modpack and connect to the server.  Both client and server need the origins mod.
