### ISSUE TITLE
Mod suggestion: Earthbounds

### ISSUE THREAD

**Issue by Klyser8** [gamerpotion/DarkRPG#2]
Hey!

As I am not sure where to suggest a mod addition to the modpack, I am doing it here.

I am the developer of Earthbounds, a mod which looks to enhance the vanilla experience of Minecraft through balanced and unique items and mobs. I am aware that the modpack's focus isn't exactly to keep the vanilla feeling of Minecraft intact, but I do believe that the mod would still be a good minor addition to the modpack. Feel free to take a look at the mod page and see for yourself if it's worth your time or not :)

https://www.curseforge.com/minecraft/mc-mods/earthbounds

**Comment by gamerpotion** [comment]
Hey :) thanks for getting in touch!
sure will take a look into this.
