### ISSUE TITLE
Cannot pickup items after die

### ISSUE THREAD

**Issue by OVDM1** [gamerpotion/DarkRPG#20]
When I died and returned to get my items I was unable to get them and I cannot pickup any block or item anymore

**Comment by gamerpotion** [comment]
> When I died and returned to get my items I was unable to get them and I cannot pickup any block or item anymore

hi, can you please confirm the modpack version you are using?

**Comment by OVDM1** [comment]
3.1b2

**Comment by DMCK96** [comment]
This occurs to me, but further if I then log out after this it forces me to recreate my character. 

Here is my latest.log with it happening: https://gnomebot.dev/paste/997517289119305898

**Comment by gamerpotion** [comment]
Please upgrade to 3.1c and see if it still happens

The keep inventory mod should be enabled and you shouldnt be losing items, they should be in inventory after you respawn

**Comment by DMCK96** [comment]
Appears to be fixed for me now, cheers.

**Comment by OVDM1** [comment]
It appears to be fixed with v 3.1c, thanks.

**Comment by gamerpotion** [comment]
Great thanks for confirming
