### ISSUE TITLE
Unable to add operators on server

### ISSUE THREAD

**Issue by JansKay** [gamerpotion/DarkRPG#26]
I am launching this pack on a multiplayer SMP and am unable to add people (including myself) as an operator. When I am in the console it gives me an error:

An unexpected error occurred trying to execute that command

Is this a "me" problem? Or a pack problem?

**Comment by gamerpotion** [comment]
> I am launching this pack on a multiplayer SMP and am unable to add people (including myself) as an operator. When I am in the console it gives me an error:
> 
> An unexpected error occurred trying to execute that command
> 
> Is this a "me" problem? Or a pack problem?

Hi,
what command are you using in the console?

in the console you should use
op xxxxx

if in game use  /op xxxxx

where xxxx is the name of your player


to remove them as op you will have to use 
deop xxxx    (in console)
/deop xxxx    (in game)
