### ISSUE TITLE
Adding Cosmetica

### ISSUE THREAD

**Issue by eyezahhhh** [gamerpotion/DarkRPG#27]
Hi! Cosmetica dev here, noticed that Cosmetica was recently removed from the modpack (Fabric). Could you tell me what issues you had with the mod? We're always looking to improve!

_ps: we dropped a huge new update a few days ago! Would be awesome if you could give me your feedback on the new features as well._

**Comment by gamerpotion** [comment]
> Hi! Cosmetica dev here, noticed that Cosmetica was recently removed from the modpack (Fabric). Could you tell me what issues you had with the mod? We're always looking to improve!
> 
> _ps: we dropped a huge new update a few days ago! Would be awesome if you could give me your feedback on the new features as well._

Hey :)
great mod! however, some users have not liked the start chat message as we need to show instructions in the modpack and it hides it
if you could enable an option to disable that?  is it possible,  
I did message on CF but not sure you saw that

**Comment by eyezahhhh** [comment]
Ah that's fair enough, is this the message telling old users that they need to update the mod, or the welcome message telling them how to equip cosmetics?

**Comment by valoeghese** [comment]
brb speedruning any% add new cosmetica feature

**Comment by gamerpotion** [comment]
> Ah that's fair enough, is this the message telling old users that they need to update the mod, or the welcome message telling them how to equip cosmetics?

ah yeah, it says to update 1.20 or something
if we could disable that, it would be super,  or have the update message in the character customization section?

**Comment by eyezahhhh** [comment]
It would be a better idea to have the modpack use the latest version of the mod, since the version you previously used (1.1.1) won't be supported in future. It uses pretty inefficient authentication methods and the logs aren't as secure as the latest mod's (1.2.0).

Either way, we're currently setting it up so you can disable non-vital update messages as well as the welcome message. But yeah would be great if you tried out the latest version, it's a huge improvement and you no longer need to use the website for choosing cosmetics, it's all in game!

**Comment by gamerpotion** [comment]
> It would be a better idea to have the modpack use the latest version of the mod, since the version you previously used (1.1.1) won't be supported in future. It uses pretty inefficient authentication methods and the logs aren't as secure as the latest mod's (1.2.0).
> 
> Either way, we're currently setting it up so you can disable non-vital update messages as well as the welcome message. But yeah would be great if you tried out the latest version, it's a huge improvement and you no longer need to use the website for choosing cosmetics, it's all in game!

could you tick the checkbox for Fabric in files for 1.2.0 ?   its not showing on CF client so cant add that unfortunately
ok will test it out,  in-game edit sounds interesting.  if you have tried our modpack's mmo server, the users would be very happy with that

**Comment by eyezahhhh** [comment]
Looks like one release of 1.2.0 was marked as Quilt only when it actually works on both. Should be updated now but CF servers aren't exactly known for their speed.

**Comment by gamerpotion** [comment]
> Looks like one release of 1.2.0 was marked as Quilt only when it actually works on both. Should be updated now but CF servers aren't exactly known for their speed.

Thanks! working now,
am very impressed with the new options,  the new things added a really nice,   have included the mod now

**Comment by eyezahhhh** [comment]
Glad to hear it.

If you're interested, contact me on discord **eyezah#5270**. We've got a cool extra feature that modpacks can utilize that we keep a little under the radar.

**Comment by valoeghese** [comment]
I didn't really introduce myself earlier... Hi! I'm the other Cosmetica dev.

I've added a couple new config options to the mod to toggle some of the in-game messages you can get on startup. The version with these will be released once the beta testers make sure I didn't introduce any new bugs.

**Comment by gamerpotion** [comment]
> I didn't really introduce myself earlier... Hi! I'm the other Cosmetica dev.
> 
> I've added a couple new config options to the mod to toggle some of the in-game messages you can get on startup. The version with these will be released once the beta testers make sure I didn't introduce any new bugs.

Hey!  :) nice to meet you too

thats awesome, cant wait to see that, thanks for making this nice mod too

**Comment by valoeghese** [comment]
The latest version (1.2.1) is out on curseforge now, with a new option in the settings file called `honestly-believe-me-i-know-what-the-heck-i-am-doing-trust-me-bro-ask-joe-if-you-dont-believe-me` you can enable in order to not display non-vital update messages ;)

**Comment by valoeghese** [comment]
We're delaying showing the 'update cosmetica' chat message 1.2.0 users to give time for packs to update to 1.2.1

**Comment by gamerpotion** [comment]
> We're delaying showing the 'update cosmetica' chat message to 1.2.0 users for a week to give time for packs to update to 1.2.1

Hey :) thanks for the update on this! I had updated the modpack yesterday and used 1.2.1 (and updated some other mods too)  however users said on servers they couldnt use commands and were getting an error - https://github.com/gamerpotion/DarkRPG/issues/30

do you know if the new update affects that in any way. I will try and update it on the modpack soon

**Comment by valoeghese** [comment]
I don't think that error looks like us. we don't use brigadier

**Comment by gamerpotion** [comment]
thanks, yeah I updated cosmetica now, all is working well :)
