### ISSUE TITLE
Mod addition suggestions

### ISSUE THREAD

**Issue by AHilyard** [gamerpotion/DarkRPG#28]
Hi there, hopefully mod suggestions are acceptable as github issues.  I couldn't find a more appropriate avenue unfortunately.

I would like to suggest the addition of a few quality of life mods that I developed and I think fit very well for inclusion in the Fabric version of the pack.  (Most of these are already present in the Forge version.)
These mods are:

- [Advancement Plaques](https://www.curseforge.com/minecraft/mc-mods/advancement-plaques-fabric)
- [Item Borders](https://www.curseforge.com/minecraft/mc-mods/item-borders-fabric)
- [Item Highlighter](https://www.curseforge.com/minecraft/mc-mods/item-highlighter-fabric)
- [Equipment Compare](https://www.curseforge.com/minecraft/mc-mods/equipment-compare-fabric)

Thank you for your time. 😄

**Comment by gamerpotion** [comment]
> 

Hey :)
interestingly I had these in old versions but for some reason they got taken out, i think it was when forge config api had an error so we disabled everything linked to that

I will add that next no worries ;)

**Comment by AHilyard** [comment]
Great to hear you're adding them back, I didn't realize they were in an earlier release!  Please let me know if you run into issues with them and I'll be happy to look into it for you. :)
