### ISSUE TITLE
4.0.6 is missing some player classes

### ISSUE THREAD

**Issue by DKrest** [gamerpotion/DarkRPG#29]
Some of the most lulz-generating classes (like crabs and slimes) are missing from a new player creation workflow.

**Comment by gamerpotion** [comment]
> Some of the most lulz-generating classes (like crabs and slimes) are missing from a new player creation workflow.

Hi sorry, due to server errors the Grounded origins and Mob Origins had to be taken out, when the issues are fixed on their side we can re-add it again

**Comment by DKrest** [comment]
@gamerpotion awesome, mate, thank you so much for the pack!
