### ISSUE TITLE
pressing i

### ISSUE THREAD

**Issue by SNOON242** [gamerpotion/DarkRPG#30]
it says to press i for stats or skills i cant remember but whenever i press i i get this error 
![image](https://user-images.githubusercontent.com/60614665/189242041-b68b5762-0757-4cbc-b532-def12fb69df1.png)

**Comment by gamerpotion** [comment]
> it says to press i for stats or skills i cant remember but whenever i press i i get this error ![image](https://user-images.githubusercontent.com/60614665/189242041-b68b5762-0757-4cbc-b532-def12fb69df1.png)

Hi, what version of the modpack are you running? and are you seeing this on the mmo server,  your own server or in singleplayer?

**Comment by gamerpotion** [comment]
Please update to 4.1.6 where this issue should now be resolved.
