### ISSUE TITLE
Launching the Game

### ISSUE THREAD

**Issue by Kiwicast** [gamerpotion/DarkRPG#32]
Hi

I am using Bisect Hosting to host my sever.
I did the one click install and that was fine.
However I then loaded the modpack from here and started the game
Once the game has loaded it give you the three options: Start Journey/MMO/Dark Realms
I go to start MMO and put in my server address and things start loading in then I get this error:

![Screenshot 2022-09-19 001845](https://user-images.githubusercontent.com/113838580/190902556-950ee04f-9b5c-49f2-842a-770e52a37a57.png)

**Comment by gamerpotion** [comment]
> Hi
> 
> I am using Bisect Hosting to host my sever. I did the one click install and that was fine. However I then loaded the modpack from here and started the game Once the game has loaded it give you the three options: Start Journey/MMO/Dark Realms I go to start MMO and put in my server address and things start loading in then I get this error:
> 
> ![Screenshot 2022-09-19 001845](https://user-images.githubusercontent.com/113838580/190902556-950ee04f-9b5c-49f2-842a-770e52a37a57.png)

Hi, please update your modpack to version 4.2.6.  
It should still work with the latest server on bisect,
let me know if it has any issues

**Comment by Kiwicast** [comment]
Hi,

I had tried 4.2.6 but still didnt work. However when Bisect asked me what version of the mod pack I was using I told them both 4.2.5 and the 4.2.6 and it still did it. I looked into the files and they are still loading the servers with 4.2.3 and as soon as I downgraded the modpack to 4.2.3 it just started working,

**Comment by gamerpotion** [comment]
Version 4.2.3
- Added Amethyst Imbuement mod
- Updated starter items to only include 1 bowl item (rabbit stew)

Ah sorry I forgot I added that mod in 4.2.3.  

ok I will upload a server pack that will fix that issue and make it up to date,   in the mean time please use 4.2.3

then later on you should be able to use 4.2.7

**Comment by gamerpotion** [comment]
> Hi,
> 
> I had tried 4.2.6 but still didnt work. However when Bisect asked me what version of the mod pack I was using I told them both 4.2.5 and the 4.2.6 and it still did it. I looked into the files and they are still loading the servers with 4.2.3 and as soon as I downgraded the modpack to 4.2.3 it just started working,

just to update, that you can now install 4.2.7 on bisect and use the 4.2.7 modpack and it will work completely fine
