### ISSUE TITLE
Sorry but..

### ISSUE THREAD

**Issue by Kanaky351** [gamerpotion/DarkRPG#33]
You should have stayed in 1.19, the server is very badly optimized in 1.19.2.  I'm sure most of the players who have experienced 1.19 have noticed the difference.
I'm going to switch to another server until things stabilize. Good luck to you

**Comment by gamerpotion** [comment]
> 

hi, what do you mean by badly optimized? do you meean server lag?  we are monitoring it daily and the tps is staying at 20 most of the time,

in fact 1.19.2 has fewer mods and less mob-related mods which is actually benefiting the server in performance
