### ISSUE TITLE
Crashes on occasion

### ISSUE THREAD

**Issue by Kiwicast** [gamerpotion/DarkRPG#34]
Just want to send you my server start up log, having a few crashes every so often, and the imbuing table when you use the EMI caused the server to crash.
Can you take a look it has errors and a few things, i know these servers are never perfect but need to check. 

[server startup.txt](https://github.com/gamerpotion/DarkRPG/files/9596075/server.startup.txt)
Thanks!

**Comment by Kiwicast** [comment]
Using bisect hosting, modpack version 4.2.7 (fabric 1.19.2)

**Comment by gamerpotion** [comment]
> Using bisect hosting, modpack version 4.2.7 (fabric 1.19.2)

Hi, this issue should be resolved in 4.3.0 and higher updates, please update to the latest version
