### ISSUE TITLE
1.19.2

### ISSUE THREAD

**Issue by erikepic** [gamerpotion/DarkRPG#35]
Hey I wanted to know how to turn off keep inventory. I tried using the in game command but its still on.

**Comment by gamerpotion** [comment]
> Hey I wanted to know how to turn off keep inventory. I tried using the in game command but its still on.

Hi, its due to a mod, go to Mods from the game menu, then look for Configured Keep Inventory, click on its options button, go to Features, and Reset the drop rate to 100
