### ISSUE TITLE
Infinite Absorption Hearts

### ISSUE THREAD

**Issue by LiamTBN** [gamerpotion/DarkRPG#38]
Ran into an issue recently using the trinkets from amethyst imbuement on my server with my friends. Some of these trinkets give absorption hearts, however whenever you relog, or take the trinkets off and put them back on after the "shielding" effect has worn off, the hearts stay and it adds 4 new absorption hearts. We're currently running version 4.4.4 till BOMD gets added back in, this was an issue in 4.4.3 as well. This is kinda game breaking because my friend ended up with 5 rows of absorption hearts.

**Comment by gamerpotion** [comment]
> Ran into an issue recently using the trinkets from amethyst imbuement on my server with my friends. Some of these trinkets give absorption hearts, however whenever you relog, or take the trinkets off and put them back on after the "shielding" effect has worn off, the hearts stay and it adds 4 new absorption hearts. We're currently running version 4.4.4 till BOMD gets added back in, this was an issue in 4.4.3 as well. This is kinda game breaking because my friend ended up with 5 rows of absorption hearts.

hi, thanks for the update. The author is working on a new version which should hopefully fix that,
I will try and include it in 4.4.6

sadly the BOMD devs have not yet updated. I have also messaged them but havent seen an update, maybe they are working on it

**Comment by gamerpotion** [comment]
hi, the new version is now active, please update to 4.4.6 which should fix the shielding issues
