### ISSUE TITLE
Mod Suggestion: Droplight

### ISSUE THREAD

**Issue by Banzetta** [gamerpotion/DarkRPG#39]
Hopefully you accept mod requests here, I couldn't find anywhere better to post this.
I would like to suggest including my new mod Droplight in the modpack, since I feel like it fits perfectly with the theme of the pack.
This mod adds new features to item drops, including new sound and visual effects.  I've already tested the mod in the pack and it works great.

Here are some screenshots to show what the mod does:
<img src="https://user-images.githubusercontent.com/111855319/196010234-fd1de79c-d089-4f2e-985c-52cde2be6c6d.png" height="430"></img> ![droptossing2](https://user-images.githubusercontent.com/111855319/196010239-77524149-ff25-4402-ad36-553c78aaae3f.gif)

Here is the CurseForge link:  https://www.curseforge.com/minecraft/mc-mods/droplight
Thank you for your consideration.

**Comment by gamerpotion** [comment]
Hey! that looks super neat! am loving the effects and will check it out now

Just wondering is this client side or both client and server side?

Our modpack comes with an official server which has been having some stability issues lately so need to make sure the mods wont affect performance etc

**Comment by Banzetta** [comment]
It is both client and server side since it affects how items are dropped from mobs.  However, in my tests there is no performance impact on the server side. 
On the client side, there are a few quality options that can be changed which will affect how much impact the visual effects have on performance.
