### ISSUE TITLE
Village Raids Stuck on 1-2 Raiders Left

### ISSUE THREAD

**Issue by arcadeemporia** [gamerpotion/DarkRPG#4]
I'm unsure if this is a feature of a mod that I'm just not aware of but as of current it's impossible to complete a raid in a village because no matter what command you run or situation you engineer, it always states that there are between 1-2 raiders left right before completion. I've already done the basic things like teleporting all raider entities to my location and combing through cave systems below the village, but nothing seems to work. Subsequent raids (triggered with changing difficulty on/off peaceful and manually applying bad omen) have increased in size, suggesting that it's recognizing the prior raids have been completed somehow but refusing to acknowledge it ingame.

**Comment by arcadeemporia** [comment]
sorry if I've not submitted this correctly or if the formatting is off, I literally made this account just to ask about this lmao

**Comment by gamerpotion** [comment]
Hi, thanks for the update on this. It could be a mod that may be doing that..
could you try to disable the following mods and see if it resolves after disabling them?
- Minecraft Dungeons Weapons mod
- Minecraft Dungeons Armor mod
- Minecraft Dungeons Artifacts mod
- GolfIV
- Minecraft Comes Alive - MCA Reborn (disable this separate to the rest to make sure its causing the issue)

did you also try the steps found here - [https://west-games.com/minecraft-raid-not-ending/](https://west-games.com/minecraft-raid-not-ending/)

**Comment by arcadeemporia** [comment]
Thank you for responding so quickly!! I've attempted all of the solutions in the article so I'm fairly certain the issue stems from one of the mods. I will do as suggested and see if that works. Thank you so much!

**Comment by gamerpotion** [comment]
> Thank you for responding so quickly!! I've attempted all of the solutions in the article so I'm fairly certain the issue stems from one of the mods. I will do as suggested and see if that works. Thank you so much!

Hey thanks for the update :)

If you try disabling the MCA mod first and see if thats the culprit, then disable the other ones too to see.
Sorry I am not able to replicate the issue at this time so cannot test but if you do find something it will be useful to others facing similar issues ;)
