### ISSUE TITLE
Strange compatibility issue with Arcanus and some other mod?

### ISSUE THREAD

**Issue by CammiePone** [gamerpotion/DarkRPG#42]
Hi! Im Cammie, the developer of Arcanus. I've noticed a strange trend in recent bug reports for Arcanus, and that is Solar Strike doesnt go away under certain circumstances. The strange thing though is that they all have one thing in common: they're all using it in Dark RPG.

Out of the 7 or so people that have reported this issue in the past few days, they've all said they were running the Dark RPG modpack. At this point, Im not totally convinced some other mod isn't interfering with the Solar Strike entity's ability to despawn after a short period of time. I havent had time to test and try and reproduce the bug on my own yet, but here's the link to the bug report on Arcanus' repo:
https://github.com/CammiePone/Arcanus/issues/76

**Comment by gamerpotion** [comment]
> Hi! Im Cammie, the developer of Arcanus. I've noticed a strange trend in recent bug reports for Arcanus, and that is Solar Strike doesnt go away under certain circumstances. The strange thing though is that they all have one thing in common: they're all using it in Dark RPG.
> 
> Out of the 7 or so people that have reported this issue in the past few days, they've all said they were running the Dark RPG modpack. At this point, Im not totally convinced some other mod isn't interfering with the Solar Strike entity's ability to despawn after a short period of time. I havent had time to test and try and reproduce the bug on my own yet, but here's the link to the bug report on Arcanus' repo: [CammiePone/Arcanus#76](https://github.com/CammiePone/Arcanus/issues/76)

Hey! :) thanks for letting me know about this. I have updated the pack and disabled solar strike in config for now. I wonder what could be causing that bug, if its a mod interfering or server lag,  Will ask around if others have also faced this on the server

**Comment by CammiePone** [comment]
someone found the mod causing the problem btw. it's ServerCore. reported it to them so hopefully a fix is released soon!

**Comment by CammiePone** [comment]
alright, there should be a new version of ServerCore out that fixes this issue completely @gamerpotion

**Comment by gamerpotion** [comment]
> alright, there should be a new version of ServerCore out that fixes this issue completely @gamerpotion

Hey :) thanks for the update on this! sorry for the late response.
will take a look into this now

Also, Just wondering if you had the chance to disable the icarus config issue if possible?
