### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by bornedead** [gamerpotion/DarkRPG#43]
Hello! so every time when i try to join my online server with darkrpg 4.6.0 server pack it showing this
![314396865_527409815918872_7676368371392305263_n](https://user-images.githubusercontent.com/117388192/199801725-3a86652d-0679-4cd8-af45-e05611278b4c.png)
any idea why? i draged every folders to my hosting and i have the same modes like on the server :pp

**Comment by gamerpotion** [comment]
Hi, you will need to make sure all the files are uploaded properly.  Use a FTP client and check. Also you need to use the same version of the modpack to connect to it. 
it might be worth wiping all the files, and re-uploading again

**Comment by bornedead** [comment]
the problem with it is that i did everything u told here and it still dosent want to work
do u have discord so we could contact ?

**Comment by gamerpotion** [comment]
> the problem with it is that i did everything u told here and it still dosent want to work do u have discord so we could contact ?

it looks like you are using an old version perhaps (the tips formatting on lower left is from old version)

get the serverpack files from here - https://www.curseforge.com/minecraft/modpacks/darkrpg/files/4061523
then the modpack itself from here - https://www.curseforge.com/minecraft/modpacks/darkrpg/files/4061468

**Comment by bornedead** [comment]
maybe that why the server didint wanted to let me join?

**Comment by gamerpotion** [comment]
> so i did everything again and nothing works maybe u can help me ?

Hi, there are 2 versions of this modpack.

1 - FORGE

2 - FABRIC

you need to choose which one and use the correct files.

If its forge then you need to download these files

Modpack - https://www.curseforge.com/minecraft/modpacks/darkrpg-forge/files/4056629
Serverpack - https://www.curseforge.com/minecraft/modpacks/darkrpg-forge/files/4056680

IF you want to play on the official server (FABRIC version)
then you just need the modpack - https://www.curseforge.com/minecraft/modpacks/darkrpg
and click on MMO and join the server that way.
if you want your own server, then use the FABRIC serverpack from here - https://www.curseforge.com/minecraft/modpacks/darkrpg/files/4068549
