### ISSUE TITLE
Dark Tides Night vision won't turn off

### ISSUE THREAD

**Issue by tracyd7177** [gamerpotion/DarkRPG#44]
After I activate Dark Tides night vision comes on  and stays on any time I go in the dark like in caves! How do I stop that?

**Comment by gamerpotion** [comment]
> After I activate Dark Tides night vision comes on and stays on any time I go in the dark like in caves! How do I stop that?

Hi, are you playing on a server or singleplayer?    The DarkTides status effects last 5 mins each time they are activated,  and sometimes on servers it can take some time to deactivate. It uses only vanilla status effects so should be working as normal

also is it switching off then on again?

**Comment by tracyd7177** [comment]
Ok I'm playing on a single player world. The effect starts over at 12 seconds anytime I'm in a cave. It won't turn off until I go to the surface. I deleted DarkTides and it still does it so it's not DT making the effect, it has to be something else. Could it be the RPG levels? Like after Mining Level 50 or so is it automatic? Idk!?

**Comment by tracyd7177** [comment]
Also it's only Night Vision that won't turn off.

**Comment by gamerpotion** [comment]
> Ok I'm playing on a single player world. The effect starts over at 12 seconds anytime I'm in a cave. It won't turn off until I go to the surface. I deleted DarkTides and it still does it so it's not DT making the effect, it has to be something else. Could it be the RPG levels? Like after Mining Level 50 or so is it automatic? Idk!? Also it's only Night Vision that won't turn off. It seems to have started after one of the recent modpack updates.

Ok, glad its not DarkTides but I also think it might not be RPGstats either. If you see their wiki - https://github.com/SilverAndro/RPGStats/wiki/Mining
it says its only meant to turn on after below y40

can you check if you have any trinkets equiped that might be giving it?

if you press E, then does it show nightvision icon? if so, if you hover it.. does it show a timer or not?
