### ISSUE TITLE
Removed # missing powers from origins: #  "error"

### ISSUE THREAD

**Issue by tridoxx** [gamerpotion/DarkRPG#45]
Hello everyone, I hope you are well and thank you beforehand for the construction of this modpack, I would like to ask why this error is due, and does it not really affect the game? We can choose classes and they work without problem, and also ask when it will be updated to the other mods of the fabric version like the sculker and the other classes thank you very much

![image](https://user-images.githubusercontent.com/22879539/202550512-77fc2e59-d24b-41d2-9630-1ef118653327.png)

**Comment by gamerpotion** [comment]
> Hello everyone, I hope you are well and thank you beforehand for the construction of this modpack, I would like to ask why this error is due, and does it not really affect the game? We can choose classes and they work without problem, and also ask when it will be updated to the other mods of the fabric version like the sculker and the other classes thank you very much
> 
> ![image](https://user-images.githubusercontent.com/22879539/202550512-77fc2e59-d24b-41d2-9630-1ef118653327.png)

Hi are you playing this on a private server? it looks as if some files have not been uploaded properly

**Comment by tridoxx** [comment]
hi   @gamerpotion  yep, is private server i am using  https://www.curseforge.com/minecraft/modpacks/darkrpg-forge , this datapack for forge, but i detect that this packet don't have the same roles, like skulcker sensor. that are in the fabric pack, maybe are not implementen yet. and ty for this great mod

**Comment by gamerpotion** [comment]
> hi @gamerpotion yep, is private server i am using https://www.curseforge.com/minecraft/modpacks/darkrpg-forge , this datapack for forge, but i detect that this packet don't have the same roles, like skulcker sensor. that are in the fabric pack, maybe are not implementen yet. and ty for this great mod

Hi, yes you cannot use the Fabric Modpack with the Forge version.
You need to make sure all server files are for Forge and the modpack connecting to it are also Forge.
Then also make sure all your files are properly uploaded via FTP
