### ISSUE TITLE
Permanent skulk sound on player

### ISSUE THREAD

**Issue by Shyefox** [gamerpotion/DarkRPG#46]
Starting out, a player on our server decided to start skulk to see what/where the spawn area for it was. After a long period of time and countless updates later, they finally asked how other people aren't annoyed by the "constant sound" on the server. Naturally, we looked into it and even had them share their screen and audio and sure enough they're constantly hearing the skulk sound no matter where they go or what they do, sometimes being a bit delayed in "following" their character, but only they hear it, nobody else. I'm thinking them starting skulkling may have flagged their character for the audio even though they race changed within the first 5 minutes and have tried many more race/class changes over the course trying to fix it. Hoping someone might have a solution short of wiping their player data entirely and all their levels and whatnot with it.

**Comment by gamerpotion** [comment]
> Starting out, a player on our server decided to start skulk to see what/where the spawn area for it was. After a long period of time and countless updates later, they finally asked how other people aren't annoyed by the "constant sound" on the server. Naturally, we looked into it and even had them share their screen and audio and sure enough they're constantly hearing the skulk sound no matter where they go or what they do, sometimes being a bit delayed in "following" their character, but only they hear it, nobody else. I'm thinking them starting skulkling may have flagged their character for the audio even though they race changed within the first 5 minutes and have tried many more race/class changes over the course trying to fix it. Hoping someone might have a solution short of wiping their player data entirely and all their levels and whatnot with it.

Hi can you confirm if you are using the Fabric or Forge version of the modpack?
and what version number?

**Comment by Shyefox** [comment]
Fabric, issue was rendered ~4.4.0 through to our current 4.7.9

**Comment by gamerpotion** [comment]
> Fabric, issue was rendered ~4.4.0 through to our current 4.7.9

Ok. I have contacted the author of the mod about this issue.

**Comment by gamerpotion** [comment]
> Fabric, issue was rendered ~4.4.0 through to our current 4.7.9

Hi, we have removed the mod in latest releases. If there is an update for it we can add it back in.
