### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by emilx10** [gamerpotion/DarkRPG#47]
the game crashes after pressing the button "E" so we cant use the inventory , we also tried a different key bind but it didnt work

**Comment by Kresei** [comment]
game crashes before even game launch

**Comment by gamerpotion** [comment]
> the game crashes after pressing the button "E" so we cant use the inventory , we also tried a different key bind but it didnt work

Hi Please update to 4.8.8 which should solve this issue

**Comment by gamerpotion** [comment]
> game crashes before even game launch today was update

Hi Please update to 4.8.8 which should solve this issue
