### ISSUE TITLE
Forbidden & Arcanus

### ISSUE THREAD

**Issue by sa3sa3103** [gamerpotion/DarkRPG#48]
That day, I was playing with my friends, I wanted to craft Eternal Stella and I found an issue that hephaestus forge didn't work. I don't know what modes cause this situation so I search on google immediately, then, nothing useful.

**Comment by gamerpotion** [comment]
> That day, I was playing with my friends, I wanted to craft Eternal Stella and I found an issue that hephaestus forge didn't work. I don't know what modes cause this situation so I search on google immediately, then, nothing useful.

Hi sorry for the late reply. Unfortunately I am not having time to looking info the forge version issues right now. If its not working as intended, it sounds like an issue with the mod itself to which I would advise raising a ticket on the Mod's github - https://github.com/stal111/Forbidden-Arcanus/issues and see if they can advise on that?
