### ISSUE TITLE
Suggested mod: Fast leaf decay

### ISSUE THREAD

**Issue by Thunder-Nova** [gamerpotion/DarkRPG#52]
There are multiple Fabric mods that have a fast leaf decay so you can choose which ever you want. Though... the biggest reason for those is for those huge trees, even with the enchantment for vein mining, early game, even late game this is just simply better.

Here are the options (They all have fabric up to 1.19, and if there is a problem with one might try another):
[Accelerated decay](https://www.curseforge.com/minecraft/mc-mods/accelerated-decay)
[Leaf Decay](https://www.curseforge.com/minecraft/mc-mods/leaf-decay)
[Fast Leaf Decaying](https://www.curseforge.com/minecraft/mc-mods/fld)

**Comment by gamerpotion** [comment]
> There are multiple Fabric mods that have a fast leaf decay so you can choose which ever you want. Though... the biggest reason for those is for those huge trees, even with the enchantment for vein mining, early game, even late game this is just simply better.
> 
> Here are the options (They all have fabric up to 1.19, and if there is a problem with one might try another): [Accelerated decay](https://www.curseforge.com/minecraft/mc-mods/accelerated-decay) [Leaf Decay](https://www.curseforge.com/minecraft/mc-mods/leaf-decay) [Fast Leaf Decaying](https://www.curseforge.com/minecraft/mc-mods/fld)

Hi, thanks for the mod links.   I did look into leaf decay some time ago but there was severe lag in particular BYG biomes with the leaf decay enabled hence it was never added. We could do some more testing on those one and see if they can be added

**Comment by Thunder-Nova** [comment]
Sure thing
