### ISSUE TITLE
Issues with server

### ISSUE THREAD

**Issue by Bheart210** [gamerpotion/DarkRPG#53]
Can't load my server because this is all it says. It was fine this morning at 8am and now at pm it says this.
![20221227_152949](https://user-images.githubusercontent.com/121521296/209724215-f824d1f6-152e-47c2-bfc6-83e9eadde600.jpg)

![20221227_152956](https://user-images.githubusercontent.com/121521296/209724209-59d48cad-7d36-4011-89f9-79ef18037454.jpg)

**Comment by gamerpotion** [comment]
> Can't load my server because this is all it says. It was fine this morning at 8am and now at pm it says this. ![20221227_152949](https://user-images.githubusercontent.com/121521296/209724215-f824d1f6-152e-47c2-bfc6-83e9eadde600.jpg)
> 
> ![20221227_152956](https://user-images.githubusercontent.com/121521296/209724209-59d48cad-7d36-4011-89f9-79ef18037454.jpg)

Hi,  2 new mods were added in the latest update, so please update your modpack to the latest version 4.9.7. The server should also be updated to that version if not already

**Comment by Bheart210** [comment]
Omg thank you so much I was worried I lost my new favorite server

**Comment by gamerpotion** [comment]
No worries.  
There is a new update that has some fixes (4.9.8) you may have to update to that at some point. Enjoy :)
