### ISSUE TITLE
ModPack incompatibility

### ISSUE THREAD

**Issue by Charlesthe12** [gamerpotion/DarkRPG#54]
The 'DarkRPG' modpack is seemingly incompatible with the 'Bits and Chisels' mod which is a real shame as the mod pack features the ability to shrink yourself at the beginning of the game but without some small mod you can't really take advantage of it.

**Comment by gamerpotion** [comment]
> The 'DarkRPG' modpack is seemingly incompatible with the 'Bits and Chisels' mod which is a real shame as the mod pack features the ability to shrink yourself at the beginning of the game but without some small mod you can't really take advantage of it.

hi i have tested this and it seems to work fine but you may also need other mods like indium to work with sodium
