### ISSUE TITLE
Crashes while in Inventory

### ISSUE THREAD

**Issue by MrTailson** [gamerpotion/DarkRPG#55]
As soon as I spawn in the world, I place down the starting shulker box the games gives you, but when I attempt to shift+click the items into my inventory, it does not process, and when I start to click and drag the items into my inventory, the game crashes. Unfortunately it does not seem to be giving me a crash report, only an "Exit Code: -1". If there is a place to find the error report, please tell me so I may help get this issue resolved.

Version: 5.2.1 - Fabric
Minecraft Version: 1.19.2

**Comment by gamerpotion** [comment]
> As soon as I spawn in the world, I place down the starting shulker box the games gives you, but when I attempt to shift+click the items into my inventory, it does not process, and when I start to click and drag the items into my inventory, the game crashes. Unfortunately it does not seem to be giving me a crash report, only an "Exit Code: -1". If there is a place to find the error report, please tell me so I may help get this issue resolved.
> 
> Version: 5.2.1 - Fabric Minecraft Version: 1.19.2

Hi Could you please check if there are any log files in the root folder, it may get start with HS...

Also could you paste your latest.log file when it crashed, so replicate the crash then paste the log thanks

**Comment by MrTailson** [comment]
Okay I found the crash reports! Thank goodness. I hope this can clear things up.

[crash-2023-02-01_00.31.28-client.txt](https://github.com/gamerpotion/DarkRPG/files/10560313/crash-2023-02-01_00.31.28-client.txt)

**Comment by MrTailson** [comment]
I found out! It was because I had the Touch Screen option under mouse settings on. When you said mouse tweaks it reminded me that I had clicked it on after hearing something about it. I turned it off on the main menu and could click and move things around again without it stalling or crashing.

**Comment by gamerpotion** [comment]
Hey thats great! glad you managed to figure it out and got rid of the crashes. Am closing the case for now. Enjoy the pack! :)
