### ISSUE TITLE
I for Stats not doing anything

### ISSUE THREAD

**Issue by alexdante** [gamerpotion/DarkRPG#56]
Hi,

I'm playing 5.2.2 in singleplayer and the quest book mentions pressing "I for Stats" but nothing happens when I do. I couldn't find anything in the keybindings that looked relevant either.

Cheers.

**Comment by gamerpotion** [comment]
Hi thank you for pointing this out. We had removed rpgstats in one of the earlier updates and seems this text was not changed. Have now fixed this in 5.2.3
