### ISSUE TITLE
Juju gold crown game crash

### ISSUE THREAD

**Issue by Maha-Kuasa** [gamerpotion/DarkRPG#57]
Attempting to craft the item "Juju gold crown" will crash the game causing either your items to drop to the floor, or to disappear (which happened to myself in my hardcore world). This is happening on the most recent version of 5.2.4.

**Comment by gamerpotion** [comment]
Hi. This is a known issue with more gems mod, I had reported it to the makers last week - https://github.com/kwpugh/more_gems_fabric/issues/61
For now I would advise to not craft it till they fix it

**Comment by gamerpotion** [comment]
Mod removed in 5.2.5
