### ISSUE TITLE
Some advancements don't work 

### ISSUE THREAD

**Issue by gregest** [gamerpotion/DarkRPG#59]
I noticed some advancements never completing, for example the rotten flesh to diamond one, or the cool down one where you put water in a bucket. I tried doing everything and nothing seemed to fix it which prevents me from continuing the quests

**Comment by gamerpotion** [comment]
Hi could you tell me the exact quest names if you hove the icons so I can take a look thanks

**Comment by gregest** [comment]
Specifically "Convert rotten flesh to diamonds", neither switching to offhand or crafting the item completes it    
"Cool Down" also doesn't seem to complete no matter what I do

**Comment by gamerpotion** [comment]
the convert rotten flesh to diamonds is part of the casino line and is a repeatable quest, meaning it doesnt complete but resets again after you complete it,  same thing for the casino

what was wrong with the water bucket one?

**Comment by gregest** [comment]
Ah, didn't know that the rotten flesh one doesn't complete on purpose   

The water bucket one doesn't complete for me, I tried everything with it but it refuses to complete the quest meaning I can't unlock more quests

**Comment by gamerpotion** [comment]
I'm not at my computer right now but could you give me the exact name of that water bucket quest so I can take a look please

**Comment by gregest** [comment]
I already mentioned, it's called "Cool Down"

**Comment by gamerpotion** [comment]
> I already mentioned, it's called "Cool Down"

hi, i just tested that quest and it seems to work fine, what type of bucket are you using are you sure it isnt completed?

![](https://media.discordapp.net/attachments/964187610392199209/1074779503672438815/image.png)

![](https://media.discordapp.net/attachments/964187610392199209/1074779503953465394/image.png)

**Comment by gregest** [comment]
just trying to use a normal minecraft bucket, here is a short video showing that it just doesn't complete 

https://user-images.githubusercontent.com/56032903/218563996-584e24e2-4987-4583-a510-648f60f125e7.mp4
