### ISSUE TITLE
End portal crash

### ISSUE THREAD

**Issue by Jamin2007** [gamerpotion/DarkRPG#60]
hey, im trying to enter the end portal but whenever i do the game crashes.

does anyone know how to fix/get around this?

**Comment by gamerpotion** [comment]
> hey, im trying to enter the end portal but whenever i do the game crashes.
> 
> does anyone know how to fix/get around this?

hi, please could you paste your crashlog (found in the crashlog folder), if there is none, then replicate the crash again, then paste the latest.log file found in the logs folder in the root directory of the modpack.
that way I can see what has caused it

**Comment by gamerpotion** [comment]
hi, the modpack has been updated to 1.19.3 (version 5.4.0+)
try that and let me know if the issue still persists
