### ISSUE TITLE
Back packs cannot go on back.

### ISSUE THREAD

**Issue by ToxicShourin** [gamerpotion/DarkRPG#63]
NOTE.
I already know this issue is created by the the pack it up mod maker. I messaged him about it and all he did was ignore and delete it. So I'm suggesting a replacement solution.

PROBLEM.
Despite the super expensive crafting required the backpacks from the Pack it up mod CANNOT go in the "Backpack" slot. It stays in the inventory when the point of having a backpack is it to go in the back pack slot. Making it a very expensive shulker box which by the way a shulker box CAN go into the back pack slot freeing up a already valuable inventory slot.

SOLUTION.
Replace "Pack it up" with "Inmis" where the back packs in Inmis actually go in the back pack slot. I already tested Inmis with this mod pack and it's fully working.

**Comment by gamerpotion** [comment]
Hi. We tried to use inmis but that had a duplication bug, so we went with Pack It Up as the creator is also on our official Discord so is able to see any bugs being mentioned there.
In the recent version of 1.19.3 that shulker in backpack mod is not added as it is not yet updated sorry.
