### ISSUE TITLE
The mod pack won't launch, and the server file seems broken.

### ISSUE THREAD

**Issue by LapsisAngelus** [gamerpotion/DarkRPG#64]
Trying to launch the game after only increasing the RAM allocation will result in this error:

Failed to download file.
Name: an_ordinary_day.ogg
URL: https://resources.download.minecraft.net/fb/fb47d8c0ba3756e2c5066fcd865e866fa209ae2d
Error details: transfer closed with 6381779 bytes remaining to read
Filename on disk: fb47d8c0ba3756e2c5066fcd865e866fa209ae2d
Path: D:\curseforge\Minecraft\Install\assets\objects\fb\fb47d8c0ba3756e2c5066fcd865e866fa209ae2d
Exists: Nonexistent

On top of this, trying to launch the server from the server folder will constantly say:

Error: Could not find or load main class @user_jvm_args.txt
Press any key to continue . . .

After looking into the "main class" issue, I really can't understand what's broken there. And even after doing a clean install on CurseForge for the modpack itself... It still fails to launch properly. Unsure what's going on. A part of me wonders if the server file is failing because I changed the minecraft file path... But it shouldn't be that o_O I even looked at the java path and confirmed it should still connect properly.

**Comment by gamerpotion** [comment]
Hi what version of the pack are you trying to load?

**Comment by LapsisAngelus** [comment]
It was the latest version as of the time I posted it, but I think the issue was the JDK version. Once I installed JDK... 17 I think? Worked perfectly fine without having to install Java 8. Gotta love those small details, right? This is just a guess based on what I did and got a similar pack working.

**Comment by gamerpotion** [comment]
Great glad its all working now! :)
