### ISSUE TITLE
JEI not showing recipes

### ISSUE THREAD

**Issue by DarKBR1** [gamerpotion/DarkRPG#9]
i created a local game and i can't see the recipes because the mod doesn't want to show them

**Comment by PotatoDotJar** [comment]
@DarKBR1 This is because the JEI key bindings are not set. You will have to set the keybindings to Left Mouse and Right Mouse.

**Comment by gamerpotion** [comment]
> i created a local game and i can't see the recipes because the mod doesn't want to show them

Hi, please try the new update 1.0.5
